version: 2
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    working_directory: ~/demo_android/DemoApp
    steps:
      - checkout
       - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

