version: 2
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    working_directory: ~/demo_android/DemoApp/
    steps:
      - checkout
      
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

